### ISSUE TITLE
Show backlinks in context

### ISSUE THREAD

**Issue by Neurrone** [hikerpig/gatsby-project-kb#1]
See [the backlinks heading on this page](https://neuron.zettel.page/tutorial.html) for an example of this. The sentence which contained the backlink is rendered to provide more context.

**Comment by hikerpig** [comment]
Nice proposal, I will try to accomplish this.

**Comment by hikerpig** [comment]
v0.4.0 has this feature implemented.

**Comment by Neurrone** [comment]
Thanks!

On the [documentation page for the graph view](https://gatsby-project-kb.vercel.app/features/graph-view), I see the following backlinks entry:

• graph view: A nice interactive [[graph-view]] visualizing the relationships of your notes.

However, I was expecting this instead (since that is the link from the front page):

• Gatsby knowledge base theme: A nice interactive [[graph-view]] visualizing the relationships of your notes.

I.e, the page title doesn't appear to match.

**Comment by hikerpig** [comment]
@Neurrone Aha, current behavior is indeed strange 😂. Let me see what I can do.

**Comment by hikerpig** [comment]
> Thanks!
> 
> On the [documentation page for the graph view](https://gatsby-project-kb.vercel.app/features/graph-view), I see the following backlinks entry:
> 
> • graph view: A nice interactive [[graph-view]] visualizing the relationships of your notes.
> 
> However, I was expecting this instead (since that is the link from the front page):
> 
> • Gatsby knowledge base theme: A nice interactive [[graph-view]] visualizing the relationships of your notes.
> 
> I.e, the page title doesn't appear to match.

Fixed it in v0.4.1.

**Comment by hikerpig** [comment]
I shall close this issue since it's been implemented, if anything strange appears, please open another issue.
