### ISSUE TITLE
Rough notation support

### ISSUE THREAD

**Issue by zubayrrr** [hikerpig/gatsby-project-kb#16]
Hi, I was messing around with [gatsby-theme-code-notes](https://github.com/mrmartineau/gatsby-theme-code-notes) and I ported rough notations over to gatsby-project-kb, 
do you think this feature will be a nice addition to gatsby-project-kb?  if yes, I'll make a PR, thank you.

Here is the [demo](https://code-notes-example.netlify.app/annotations) for rough notations

**Comment by hikerpig** [comment]
Hi @zubayrrr, it's one pretty nice feature to have, but can this be provided as a seperate gatsby plugin instead of directly into the gatsby-theme-kb?

**Comment by zubayrrr** [comment]
No, unfortunately it cannot be used as a plugin, they're more like custom MDX components.

**Comment by hikerpig** [comment]
> No, unfortunately it cannot be used as a plugin, they're more like custom MDX components.
> 
> let me make a PR real quick so you can check for yourself, I'm really bad at explaining 😅

Sure. 😀
