### ISSUE TITLE
Backlink on a backlink preview seems broken

### ISSUE THREAD

**Issue by zubayrrr** [hikerpig/gatsby-project-kb#20]
![image](https://user-images.githubusercontent.com/31969517/120057413-6c38fe80-c060-11eb-8afe-25bad18376f1.png)

eg:
the "hello world" has a backlink to "graph view" which should take to ` /features/graph-view` but instead it takes to `/graph-vew`

this is only happening on backlink previews 

another eg:

![image](https://user-images.githubusercontent.com/31969517/120057605-e74ee480-c061-11eb-98fb-3a653642d812.png)

should take to `/examples/syntax-highlight` but instead takes to `/syntax-highlight`

thank you

**Comment by hikerpig** [comment]
I will look into all your issues tomorrow ｡◕‿◕｡.

**Comment by hikerpig** [comment]
This is partially fixed in v0.7.4, the link resolving is OK now.
But the wiki link title inside the popover (nested topics) is not very well supported. 
Guess I will need some rewrite of the graphql query to support this nested lookup.  Let's push it to the next version.

**Comment by zubayrrr** [comment]
@hikerpig  THank you 🙏🏽
