### ISSUE TITLE
解决图片地址问题

### ISSUE THREAD

**Issue by imhgy** [hikerpig/gatsby-project-kb#27]
您好，我的 md 文件都是采用本地存储的方式，例如：
![image](https://user-images.githubusercontent.com/44602901/133282531-8ab404b4-b101-4044-97dd-77d44f0da2bc.png)

可是在 yarn build 以后，在生成的文件中并没有将文件导出到 public 中，这个是什么问题呢？

**Comment by flashshare** [comment]
@imhgy 
我认为最好上传到imgur。 如果你使用的是 Obsidian，你可以使用这个插件 https://github.com/gavvvr/obsidian-imgur-plugin

**Comment by hikerpig** [comment]
@imhgy 是的，这个 Gatsbyjs 主题本身并不会拷贝静态目录，需要一些插件或者约定规则支持。
我看你使用的是 Obsidian ? 可以参考下这个项目的配置 https://github.com/hikerpig/foam-template-gatsby-kb，如果可以的话建议使用这个模板，对 Foam 或者 Obsidian 都能支持（我自己的 wiki 也是 Obsidian 写的）。
如果比较熟悉 Gatsby 生态的话可以自己折腾。上面的模板主要是靠 `gatsby-remark-copy-linked-files` 插件实现了提取 markdown 中的静态文件路径并自动拷贝到 public 目录的功能。

**Comment by imhgy** [comment]
@hikerpig 参照项目 foam-template-gatsby-kb 的配置处理好了，我刚刚接触 Gatsby，感谢你的帮助！
