### ISSUE TITLE
Pages with the multiple ``[[wikilinks]]`` get listed multiple times in the `Backlinks` section.

### ISSUE THREAD

**Issue by mainrs** [hikerpig/gatsby-project-kb#31]
For example page A refers to page B three times in total using `[[B]]`. The backlinks section of page B would the contain `A` three times:

![image](https://user-images.githubusercontent.com/5113257/136870173-c1ba4aa0-6763-4a66-9a5e-6834d999b0a9.png)
![image](https://user-images.githubusercontent.com/5113257/136870183-b8b2002a-e961-4f87-8433-740ffd115a68.png)

**Comment by hikerpig** [comment]
This is actually a feature, though it seems  confusing sometimes. See #12
