### ISSUE TITLE
Can't open pages that contain multiple words in their filename

### ISSUE THREAD

**Issue by andreiRS** [hikerpig/gatsby-project-kb#44]
Most PKM tools (e.g. Obsidian, Logseq, Foam) support files that contain multiple words and some special characters (e.g. " ", "-", "_").

Currently I am getting an error if I try to open a file that has space inside of its name. (e.g. "Digital Garden"). 

I would like to import my Obsidian vault and having to rename all my atomic notes to not have space in their file name is would something I would like to avoid.

Is there something I'm doing wrong?

Here are some screenshots to clarify the issue:
![CleanShot 2022-03-19 at 11 03 31@2x](https://user-images.githubusercontent.com/615110/159114928-d803e32c-fd6e-4c57-ada4-c6a3e96967fe.png)

<img width="687" alt="CleanShot 2022-03-19 at 11 00 15@2x" src="https://user-images.githubusercontent.com/615110/159114932-7334e846-e0d1-4240-b92f-6819e8c2caa5.png">

![CleanShot 2022-03-19 at 10 59 58@2x](https://user-images.githubusercontent.com/615110/159114983-4c3cd3e7-7274-41fa-b56a-630af8b6b0de.png)
![CleanShot 2022-03-19 at 10 58 28@2x](https://user-images.githubusercontent.com/615110/159114999-060da295-438b-4675-87f7-dcd738b40c2f.png)

Sample library I would like to import and eventualy sync with Obsidian:

![CleanShot 2022-03-19 at 10 55 51@2x](https://user-images.githubusercontent.com/615110/159114670-841a4adf-4c42-46df-800e-56afb530b309.png)

**Comment by hikerpig** [comment]
Thank you for posting this issue, I didn't pay attension to this for all my own notes' names are `lowercase-with-hyphen`.
I will try to fix this.

**Comment by hikerpig** [comment]
This is fixed in gatsby-theme-kb@0.9.1

**Comment by andreiRS** [comment]
Thank you ❤️ I just pulled the latest changes and the work as expcted!
