### ISSUE TITLE
Pages under folders can't be opened

### ISSUE THREAD

**Issue by andreiRS** [hikerpig/gatsby-project-kb#48]
Files under folders are not accessible, except from the sidebar. 

Expected behavior:
Files can be open independently from the location where they are stored. (Same in Obsidian, Logseq, etc.)

See screenshot:
![CleanShot 2022-03-21 at 20 05 29@2x](https://user-images.githubusercontent.com/615110/159336990-5f7276a0-e451-436c-8b13-37a529c22c9a.png)

**Comment by hikerpig** [comment]
Well I see, this is actually a bug - where name-mapping does not work perfectly when the note is in some nested folder.
I will try to fix this in this week.

**Comment by andreiRS** [comment]
Sounds good. Thanks!

**Comment by hikerpig** [comment]
@andreiRS You can try v0.9.3 to see if it's fixed.
