### ISSUE TITLE
Local images are not working

### ISSUE THREAD

**Issue by andreiRS** [hikerpig/gatsby-project-kb#50]
I tried to add images to one of the notes and when I start the server, they are not resolved.

Inside of the content folder I create a new folder called "assets" and configured both Obsidian and Logseq to use it for storing attachments or other static resources. As you can see they display the image correctly:

<img width="1290" alt="CleanShot 2022-03-23 at 08 18 32@2x" src="https://user-images.githubusercontent.com/615110/159636319-a18ff7b2-c1fd-43ba-86c8-9b80c668d8b0.png">

However the online version looks like this:
<img width="1141" alt="CleanShot 2022-03-23 at 08 17 36@2x" src="https://user-images.githubusercontent.com/615110/159636365-5e459d13-da25-4694-9f31-dcd2b9c6c357.png">

<img width="1142" alt="CleanShot 2022-03-23 at 08 17 50@2x" src="https://user-images.githubusercontent.com/615110/159636377-ac074ad6-f3cf-44f3-9ae5-c1374e550609.png">

This is how the project structure looks like:
<img width="985" alt="CleanShot 2022-03-23 at 08 18 00@2x" src="https://user-images.githubusercontent.com/615110/159636425-a273da9c-22e1-4add-96c3-75ab5ce222d7.png">

Am I doining something wrong?

**Comment by hikerpig** [comment]
This requires some extra gatsby plugins and configurations. see  https://github.com/hikerpig/foam-template-gatsby-kb#some-gatsby-configurations,  search for `gatsby-remark-copy-linked-files` and `gatsby-plugin-copy-files-enhanced`

**Comment by andreiRS** [comment]
Thanks for pointing me to the write place. I added the the extra plugins and it worked as expected.
