### ISSUE TITLE
Wikilinks with spaces in name disables link previews

### ISSUE THREAD

**Issue by jakegut** [hikerpig/gatsby-project-kb#63]
I see that https://github.com/hikerpig/gatsby-project-kb/issues/44 was resolved. However, I'm noticing that link previews don't work for wiki links (or files) with spaces in their name.

**Comment by hikerpig** [comment]
This looks well during my local test with latest version 0.9.4.
Could you provide a not working example ?
<img width="301" alt="image" src="https://user-images.githubusercontent.com/2259688/212463642-74f77516-8f40-405d-b1e7-abb05601b2be.png">
<img width="622" alt="image" src="https://user-images.githubusercontent.com/2259688/212463668-b8d1488a-1d31-43c8-ba47-05cd34cf525c.png">

**Comment by jakegut** [comment]
Looks like I was on v0.9.0 :/. Upgrading resolved the issue.
