### ISSUE TITLE
Convert wikilinks to markdown titles

### ISSUE THREAD

**Issue by SanketDG** [hikerpig/gatsby-project-kb#9]
Currently the wikilinks are rendered as it is.

Is it possible to convert `[[wikilink]]` to [[Wikilink]] or whatever the first `h1` title is?

**Comment by hikerpig** [comment]
Thank you for the feedback.
Yes, it is possible in theory, I just havn't found an elegant way to do it back then.
I will try to add this in this weekend.

**Comment by hikerpig** [comment]
@SanketDG I managed to add this feature (although still not very elegantly). You can check [the code diff](https://github.com/hikerpig/gatsby-project-kb/commit/a4f1d5502da6c86a6330941f773fc41ff7aeb39e#diff-7f7daf7ad99f59a3bbdc537532433cf19c17dc11ad549320eacc71155e009d23R17) to see how the option works.
I haven't made `[[{{title}}]]` the default option for `gatsby-theme-kb` though, so you may need to manually specify it in your config.
The latest package is `gatsby-theme-kb@0.7.2`.

**Comment by SanketDG** [comment]
I tried this out, this looks good!

Thanks so much, I am going to close this now.
